/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mustahiq;

import aplikasizakat.koneksi;
import com.sun.org.apache.bcel.internal.Constants;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SpinnerNumberModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Bernafas
 */
public class inputMustahiq extends javax.swing.JFrame {

    /**
     * Creates new form inputMuzakki
     */
    koneksi k=new koneksi();
    
    public static int nomor=0,jmlBeras;
    public static Integer total;
    public inputMustahiq() {
        initComponents();
        
        k.konek();
        setLocationRelativeTo(null);
        
        //memamnggil data dari dt_mustahiq
        String sql="select nomor from dt_mustahiq";

         try{
            k.st=k.conn.createStatement();
            k.rs=k.st.executeQuery(sql);
            try{
            k.rs.last();
                if(k.rs.last()==false){
                    nomor=nomor+1;
                }else{
                    nomor=k.rs.getInt("nomor")+1;
                }
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Gagal Query");
                return;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Gagal mengambil nomor");
            return;
        }
        txtPanitia.setText(k.username.toUpperCase());
        txtNomor.setText(Integer.toString(nomor));
        
    }
    
    //mengosongkan Field yang telah diisi
    public void setKosongkan(){
        txtNamaMustahiq.setText(null);
        txtKet.setText(null);
        cmbGolongan.setSelectedIndex(0);
        txtAlamat.setText(null);
        txtJmlUang.setText(null);
        txtJmlBeras.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtNomor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaMustahiq = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJmlUang = new javax.swing.JTextField();
        txtJmlBeras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPanitia = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbGolongan = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INPUT DATA MUZAKKI");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TANGGAL");

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMOR");

        txtTanggal.setEditable(false);
        txtTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        txtNomor.setEditable(false);
        txtNomor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PENERIMA");

        jLabel5.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ALAMAT");

        jLabel8.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JUMLAH UANG");

        txtJmlBeras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtJmlBerasMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KG");

        jLabel11.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PANITIA");

        txtPanitia.setEditable(false);
        txtPanitia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/restart.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muzakki/save(1).png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GOLONGAN");

        cmbGolongan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- PILIH GOLONGAN --", "FAKIR MISKIN", "AMILIN", "RIQOB", "GHARIMIN", "MUALLAF", "FISABILILLAH", "IBNU SABIL" }));
        cmbGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGolonganActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JUMLAH BERAS");

        txtKet.setColumns(20);
        txtKet.setRows(5);
        jScrollPane1.setViewportView(txtKet);

        jLabel6.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KETERANGAN");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PENYALURAN ZAKAT");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(".::");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("::.");

        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\meme\\tugas\\icon\\mosque.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPanitia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtJmlBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addComponent(txtJmlUang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnSimpan)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNamaMustahiq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(cmbGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlUang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlBeras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPanitia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        //button Simpan / save / tambah
        if(txtNamaMustahiq.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama Penerima Belum di Isi");
            txtNamaMustahiq.requestFocus();
        }else if(cmbGolongan.getSelectedIndex()==0 ){
            JOptionPane.showMessageDialog(null,"Golongan Belum di Pilih");
            cmbGolongan.requestFocus();
        }else if(txtAlamat.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Alamat Belum di Isi");
            txtAlamat.requestFocus();
        }else if(txtJmlUang.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Jumlah Uang Belum di Isi");
            txtJmlUang.requestFocus();
        }else if(Integer.parseInt(txtJmlUang.getText()) > daftarMustahiq.totUangMuzakki){
            JOptionPane.showMessageDialog(null,"Jumlah Uang Melebihi Jumlah Maksimal");
            txtJmlUang.requestFocus();
        }else if(Integer.parseInt(txtJmlUang.getText()) < 0){
            JOptionPane.showMessageDialog(null,"Jumlah Uang Harus Lebih Dari 0");
            txtJmlUang.requestFocus();
        }else{
            boolean proses=false;
            if(txtJmlBeras.getText().isEmpty()){
                jmlBeras=0;
                proses=true;
            }else if((!(txtJmlBeras.getText().isEmpty()))&& (Integer.parseInt(txtJmlBeras.getText()) > daftarMustahiq.totBerasMuzakki)){
                JOptionPane.showMessageDialog(null,"Jumlah Beras Melebihi Jumlah Maksimal");
                txtJmlBeras.requestFocus();
                proses=false;
            }else if((!(txtJmlBeras.getText().isEmpty()))&& (Integer.parseInt(txtJmlBeras.getText()) < 0)){
                JOptionPane.showMessageDialog(null,"Jumlah Beras Harus Lebih Dari 0");
                txtJmlBeras.requestFocus();
                proses=false;
            }else{
                jmlBeras=Integer.parseInt(txtJmlBeras.getText());
                proses=true;
            }
       //jika semua kondisi di atas sudah betul semua
       if(proses==true){
           //masukkan data ke dalam dt_mustahiq (nomor, tgl, gol blbalbalbalbla) VALUE (dari text Field yang diisi saat program berjalan)
            String sql="INSERT into dt_mustahiq (nomor,tglInput,gol,namaMustahiq,alamat,jmlUang,jmlBeras,panitia) VALUE ("+
                           nomor+",'"+
                           txtTanggal.getText()+"','"+
                           cmbGolongan.getSelectedItem()+"','"+
                           txtNamaMustahiq.getText().toUpperCase()+"','"+
                           txtAlamat.getText()+"','"+
                           txtJmlUang.getText()+"','"+
                           jmlBeras+"','"+
                           koneksi.username+"')";
            //eksekusi data
            try{
                k.st=k.conn.createStatement();
                k.st.execute(sql);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, "Penyimpanan Gagal total"+e);
                setKosongkan(); //kosongkan field, (diambil dari fungsi yang telah dibuat di atas)
                txtNamaMustahiq.requestFocus();
                return;
            }
            //jika data berhasil
            JOptionPane.showMessageDialog(this,"Data Berhasil Disimpan");
            this.dispose(); //tutup form input Mustahiq
            //new inputMustahiq().setVisible(true);
       }
        }
            
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        nomor=0;
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        setKosongkan();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGolonganActionPerformed
        // TODO add your handling code here:
        //jika golongan FAKIR MUSKIN dipilih
        if (cmbGolongan.getSelectedItem().equals("FAKIR MISKIN")) {
            //field txtKet akan berisi
            txtKet.setText("Dalam bahasa Arab, kata faaqir berasal dari kata faqr\n" +
                           "yang berarti ‘tulang punggung’ dan yang pertama (faaqir)\n" +
                           "berarti ‘orang yang patah tulang punggungnya’ karena demikian \n" +
                           "berat beban yang dipikulnya. Sedangkan kata ‘miskin’\n" +
                           "berasal dari kata sakana yang dalam bahasa Arab berarti \n" +
                           "‘diam’ atau ‘tenang’.");
        }else if(cmbGolongan.getSelectedItem().equals("AMILIN")){
            txtKet.setText("Al’Amilin atau amil zakat merupakan orang yang bertugas \n" +
                           "mengumpulkan serta membagikan zakat kepada golongan yang \n" +
                           "berhak menerimanya.Karenanya, Al-Amilin juga termasuk \n" +
                           "sebagai mustahiq zakat sehingga berhak menerima pembagian\n" +
                           "zakat yang dipilih terlebih dahulu oleh imam masjid.");
        }else if(cmbGolongan.getSelectedItem().equals("RIQOB")){
            txtKet.setText("Para penerima zakat berikutnya adalah hamba sahaya atau\n" +
                           "budak yang ingin memerdekakan dirinya dari majikan dan \n" +
                           "membutuhkan tebusan uang.Zakat bagi Dzur riqab juga mencakup\n" +
                           "pembebasan seorang muslim yang ditawan oleh orang-orang jahat, \n" +
                           "atau membebaskan seorang muslim dari penjara karena tidak\n" +
                           "mampu membayar denda atau diat.");
        }else if(cmbGolongan.getSelectedItem().equals("GHARIMIN")){
            txtKet.setText("Istilah ini merujuk pada orang yang berutang dan tidak\n" +
                           "sanggup membayar. Namun, perlu diingat bahwa utang \n" +
                           "tersebut digunakan untuk kepentingan pribadi dan bukan \n" +
                           "untuk kebutuhan maksiat.");
        }else if(cmbGolongan.getSelectedItem().equals("MUALLAF")){
            txtKet.setText("Mualaf sendiri terbagi atas tiga bagian antara lain: \n" +
                           "Orang yang masuk Islam dan hatinya masih bimbang, maka\n" +
                           "harus diberikan saran dan masukan agar mendapatkan zakat.\n" +
                           "Lalu, ada orang yang masuk Islam agar diberikan zakat \n" +
                           "bila bersungguh-sungguh belajar dan menjauhi larangan,\n" +
                           "dan yang terakhir mualaf yang adil dan perlu bimbingan.");
        }else if(cmbGolongan.getSelectedItem().equals("FISABILILLAH")){
            txtKet.setText("Fisabilillah atau Al-Muhajidin merupakan orang yang \n" +
                           "berjuang di jalan Allah (sabilillah) tanpa upah dan \n" +
                           "imbalan demi membela dan mempertahankan Islam dan kaum muslimin\n" +
                           "untuk mendapatkan hak beribadah, hak asasi manusia \n" +
                           "serta memperjuangkan kebebasan beribadah bagi seluruh umat Muslim.");
        }else if(cmbGolongan.getSelectedItem().equals("IBNU SABIL")){
            txtKet.setText("Mustahiq zakat yang terakhir adalah musafir \n" +
                           "atau orang yang sedang dalam perjalanan (ibnu sabil) \n" +
                           "yang bertujuan untuk mencari akidah, ilmu dan ridha Allah SWT.");
        }else{
            JOptionPane.showMessageDialog(this, "Form tidak boleh kosong");
            setKosongkan();
        }
    }//GEN-LAST:event_cmbGolonganActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //mengatur format tanggal
        DateFormat dateFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        txtTanggal.setText(dateFormat.format(date).toString());
    }//GEN-LAST:event_formWindowOpened

    private void txtJmlBerasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJmlBerasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBerasMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        nomor=0;
    }//GEN-LAST:event_formWindowClosed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputMustahiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputMustahiq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbGolongan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtJmlBeras;
    private javax.swing.JTextField txtJmlUang;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNamaMustahiq;
    private javax.swing.JTextField txtNomor;
    private javax.swing.JTextField txtPanitia;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
